import Notifications from './Notifications';
import {useEffect,useRef,useState} from 'react';
import {Upload,Send,RefreshCw,Pause,Play,Square,Download,ShieldCheck} from 'lucide-react';
import TemplateFields,{templateInputs,templateComplete} from './TemplateFields';
import type {TemplateValues} from './TemplateFields';
type Obj=Record<string,any>;
async function api(path:string,method='GET',body?:any){const r=await fetch('/api'+path,{method,headers:{'X-HYS-Request':'1',...(body instanceof FormData?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:d.detail?.message?d.detail.message+(d.detail.code!==undefined?' (Meta kodu: '+d.detail.code+')':''):'İşlem tamamlanamadı.');return d;}
const labels:Record<string,string>={draft:'Onay bekliyor',preparing:'Medya yükleniyor',running:'Gönderim sürüyor',paused:'Duraklatıldı',completed:'Kuyruk tamamlandı',cancelled:'Durduruldu',scheduled:'Planlandı'};
const messageLabels:Record<string,string>={queued:'Bekliyor',retry:'Bekleme sonrası yeniden denenecek',sending:'API isteği sürüyor',accepted:'API kabul etti',sent:'Gönderildi',delivered:'Teslim edildi',read:'Okundu',failed:'Başarısız',blocked:'Engellendi',uncertain:'Sonuç belirsiz',cancelled:'Durduruldu',dry_run:'Simüle edildi'};
export default function BulkPanel({user}:{user:Obj}){
 const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Obj|null>(null),[templates,setTemplates]=useState<Obj[]>([]),[templateId,setTemplateId]=useState(''),[values,setValues]=useState<TemplateValues>({});
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[review,setReview]=useState<Obj|null>(null),[campaignId,setCampaignId]=useState<number|null>(null),[progress,setProgress]=useState<Obj|null>(null),[testPhone,setTestPhone]=useState('');
 const [permitFile,setPermitFile]=useState<File|null>(null),[permitConfirmed,setPermitConfirmed]=useState(false),[permitColumns,setPermitColumns]=useState<Obj[]>([]),[permitColumn,setPermitColumn]=useState('');
 const [mediaFile,setMediaFile]=useState<File|null>(null);
 const permitInput=useRef<HTMLInputElement>(null);
 const [recipientPage,setRecipientPage]=useState(1);
 const selected=templates.find(t=>String(t.id)===templateId);
 async function loadTemplates(){try{await api('/templates/sync','POST');const ts=await api('/templates');setTemplates(ts.filter((t:Obj)=>t.status==='APPROVED'&&t.category==='MARKETING'));}catch(e){setError(String(e));setTemplates([]);}}
 useEffect(()=>{void loadTemplates();const saved=localStorage.getItem('hys-active-bulk-campaign');if(saved)setCampaignId(Number(saved));},[]);
 async function refresh(id:number){try{const p=await api('/bulk/campaign/'+id+'?page='+recipientPage);setProgress(p);}catch(e){setError(String(e));}}
 useEffect(()=>{if(!campaignId)return;void refresh(campaignId);const timer=setInterval(()=>void refresh(campaignId),3000);return()=>clearInterval(timer);},[campaignId,recipientPage]);
 async function upload(input:File,column?:number){setBusy(true);setError('');setReview(null);try{const form=new FormData();form.append('file',input);if(column!==undefined)form.append('phone_column',String(column));setPreview(await api('/bulk/preview','POST',form));setFile(input);}catch(e){setError(String(e));setPreview(null);}finally{setBusy(false);}}
 async function permissionImport(){if(!permitFile)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',permitFile);form.append('confirmed',String(permitConfirmed));if(permitColumn!=='')form.append('phone_column',permitColumn);const r=await api('/bulk/permissions/import','POST',form);if(r.needs_column){setPermitColumns(r.columns);return;}setNotice(r.imported+' izinli numara eşleştirildi; '+r.blocked+' ret/engelli numara korunarak atlandı. '+r.notice);setPermitFile(null);if(permitInput.current)permitInput.current.value='';setPermitConfirmed(false);setPermitColumns([]);setPermitColumn('');if(file){const f=new FormData();f.append('file',file);if(preview?.phone_column!==null)f.append('phone_column',String(preview?.phone_column));setPreview(await api('/bulk/preview','POST',f));}}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function prepare(){if(!selected||!preview)return;setBusy(true);setError('');try{const payload={token:preview.token,template_id:selected.id,...templateInputs(selected as any,values)};let r;if(mediaFile){const f=new FormData();f.append('data',JSON.stringify(payload));f.append('file',mediaFile);r=await api('/bulk/campaign-with-media','POST',f);}else r=await api('/bulk/campaign','POST',payload);setReview(r);setCampaignId(r.campaign.id);setTestPhone(r.recipients[0]||'');await refresh(r.campaign.id);}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function begin(test=false){if(!review)return;if(test&&!window.confirm(testPhone+' numarasına önizlemedeki mesaj bir kez '+(review.dry_run?'simüle edilsin':'gerçek olarak gönderilsin')+' mi?'))return;setBusy(true);setError('');try{const r=await api('/bulk/campaign/'+review.campaign.id+(test?'/test':'/start'),'POST',{confirmed:true,phone:test?testPhone:undefined});localStorage.setItem('hys-active-bulk-campaign',String(review.campaign.id));await refresh(review.campaign.id);setNotice(test?'Tek alıcı gönderimi kuyruğa alındı. API kabulü teslimat anlamına gelmez.':r.queued+' numara kuyruğa alındı. Önceden denenen alıcı yeniden gönderilmez.');if(!test)setReview(null);}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function action(name:string){if(!campaignId)return;if(name==='cancel'&&!window.confirm('Bekleyen gönderimler durdurulsun mu? Meta’ya ulaşmış mesajlar geri alınamaz.'))return;setBusy(true);setError('');try{await api('/campaigns/'+campaignId+'/'+name,'POST');await refresh(campaignId);}catch(e){setError(String(e));}finally{setBusy(false);}}
 const admin=user.role==='admin',canReview=!!preview?.eligible_count&&!!selected&&templateComplete(selected as any,values,mediaFile)&&!preview?.needs_column;
 return <section className="section-content bulk-page bulk-friendly">
  <div className="section-intro"><div><span className="section-kicker">İZİNLİ MÜŞTERİLERE KAMPANYA</span><h1>Toplu mesaj</h1><p>Excel'i yükleyin, onaylı şablonu seçin, alıcıları kontrol edip gönderin.</p></div><div className="bulk-safety"><ShieldCheck size={18}/>İzinler harici HYS satış programında yönetilir</div></div>
  <Notifications error={error} notice={notice} onErrorClose={()=>setError('')} onNoticeClose={()=>setNotice('')}/>
  <div className="bulk-grid"><section className="simple-card"><div className="card-heading"><span className="step-number">1</span><div><h2>Excel veya CSV yükle</h2><p>Yalnızca telefon numarası sütunu yeterli.</p></div></div>
   <label className="upload-drop"><Upload/><strong>{file?.name||'Dosya seçin'}</strong><span>XLSX, XLS, CSV · en fazla 5 MB · 10.000 dolu satır</span><input type="file" accept=".xlsx,.xls,.csv" disabled={busy} onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value='';}}/></label>
   {preview&&<><label className="simple-field">Telefon numarası sütunu<select value={preview.phone_column??''} disabled={busy} onChange={e=>file&&void upload(file,Number(e.target.value))}><option value="" disabled>Sütun seçin</option>{preview.columns.map((c:Obj)=><option key={c.index} value={c.index}>{c.name}</option>)}</select></label>
   <div className="recipient-stats">{[['eligible_count','Uygun'],['unique_count','Benzersiz'],['duplicate_count','Mükerrer atlandı'],['invalid_count','Geçersiz atlandı'],['excluded_count','İzin / ret nedeniyle atlandı'],['skipped_count','Boş satır yok sayıldı']].map(([key,label])=><div key={key}><strong>{preview[key]}</strong><span>{label}</span></div>)}</div>
   <p className="subtle-note">{preview.permission_notice}</p>
   <details><summary>Alıcıları ve atlanan satırları gör</summary><div className="bulk-recipient-list">{preview.eligible_preview.map((r:Obj)=><div key={r.phone}>{r.phone} · Uygun</div>)}{preview.excluded_rows.map((r:Obj)=><div key={r.phone}>{r.phone} · {r.reason}</div>)}{preview.invalid_rows.map((r:Obj)=><div key={r.row}>Satır {r.row}: {r.value} · {r.reason}</div>)}</div><small>Her gruptan ilk 200 kayıt gösterilir; sayılar dosyanın tamamını kapsar.</small></details></>}
   <details className="bulk-permissions"><summary>Satış programındaki izinli numaraları eşleştir</summary><p>Yalnızca WhatsApp pazarlama ve ticari ileti izinleri doğrulanmış müşterileri satış programından dışa aktarın. Telefon sütunu yeterli; izin tarihi veya belge sütunu gerekmez. Bu işlem satış programını otomatik sorgulamaz.</p><label className="simple-field">Doğrulanmış izinli liste<input ref={permitInput} type="file" accept=".xlsx,.xls,.csv" disabled={busy} onChange={e=>{setPermitConfirmed(false);setPermitFile(e.target.files?.[0]||null);setPermitColumns([]);setPermitColumn('');}}/></label>
   {!!permitColumns.length&&<label className="simple-field">İzinli listedeki telefon sütunu<select value={permitColumn} onChange={e=>setPermitColumn(e.target.value)}><option value="">Sütun seçin</option>{permitColumns.map(c=><option key={c.index} value={c.index}>{c.name}</option>)}</select></label>}
   <label className="bulk-checkbox"><input type="checkbox" disabled={!admin||busy} checked={permitConfirmed} onChange={e=>setPermitConfirmed(e.target.checked)}/>Bu dosyanın satış programında WhatsApp pazarlama ve ticari ileti izni doğrulanmış müşterilerin dışa aktarımı olduğunu yönetici olarak doğruluyorum.</label>
   {!admin&&<p className="eligibility-warning">Dosya seçebilirsiniz; izinli numaraları eşleştirmek için yönetici hesabıyla giriş yapılmalıdır.</p>}<button disabled={!admin||busy||!permitFile||!permitConfirmed||!!permitColumns.length&&permitColumn===''} onClick={()=>void permissionImport()}>İzinli numaraları eşleştir</button><small>Ret / İPTAL kayıtları bu işlemle kaldırılmaz.</small></details>
  </section><section className="simple-card"><div className="card-heading"><span className="step-number">2</span><div><h2>Mesaj şablonunu seç</h2><p>Yalnızca Meta onaylı Marketing şablonları.</p></div></div>
   <label className="simple-field">Onaylı mesaj şablonu<select disabled={busy} value={templateId} onChange={e=>{setTemplateId(e.target.value);setValues({});setMediaFile(null);setReview(null);}}><option value="">Şablon seçin</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name} · {t.language}</option>)}</select></label>
   <button disabled={busy} onClick={()=>void loadTemplates()}><RefreshCw size={15}/>Şablonları yenile</button>{!templates.length&&<p className="subtle-note">Onaylı Marketing şablonu yok veya Meta’dan doğrulanamadı. Pending / Rejected şablonlar gönderilemez.</p>}
   <TemplateFields template={selected as any} values={values} onChange={v=>{setValues(v);setReview(null);}} file={mediaFile} onFileChange={f=>{setMediaFile(f);setReview(null);}} disabled={busy}/>
   <div className="cost-row"><span>Yaklaşık ücret</span><strong>Tarife kaynağı yok · bilinmiyor</strong></div><button className="button-green large" disabled={!admin||busy||!canReview} onClick={()=>void prepare()}><Send size={17}/>Alıcıları ve mesajı kontrol et</button>{!admin&&<p>Gönderimi yalnızca yetkili yönetici başlatabilir.</p>}
  </section></div>
  {progress&&<section className="simple-card campaign-progress"><h2>{progress.campaign.name}</h2><p>{labels[progress.campaign.status]||progress.campaign.status}{progress.test_only?' · Tek alıcı denemesi':''}</p>
   {progress.queue_notice&&<p className="subtle-note">{progress.queue_notice}</p>}
   <div className="progress-track"><i style={{width:progress.total?100*(progress.total-progress.waiting)/progress.total+'%':'0%'}}/></div>
   <div className="recipient-stats">{[['waiting','Bekliyor'],['accepted','API kabul etti'],['sent','Gönderildi'],['delivered','Teslim edildi'],['read','Okundu'],['failed','Başarısız'],['blocked','Engellendi'],['uncertain','Sonuç belirsiz'],['cancelled','Durduruldu'],['dry_run','Simüle edildi']].map(([key,label])=><div key={key}><strong>{progress[key]||0}</strong><span>{label}</span></div>)}</div>
   <p className="subtle-note">API kabulü teslimat değildir. Gönderildi, teslim edildi ve okundu durumları gerçek webhook kayıtlarından güncellenir. Sonucu belirsiz mesajlar çift gönderimi önlemek için otomatik tekrarlanmaz.</p>
   <div className="approval-actions">{['running','scheduled'].includes(progress.campaign.status)&&<button disabled={!admin||busy} onClick={()=>void action('pause')}><Pause size={16}/>Duraklat</button>}{progress.campaign.status==='paused'&&<button disabled={!admin||busy} onClick={()=>void action('resume')}><Play size={16}/>Devam ettir</button>}{['running','scheduled','paused'].includes(progress.campaign.status)&&<button disabled={!admin||busy} onClick={()=>void action('cancel')}><Square size={16}/>Durdur</button>}{admin&&<a className="button" href={'/api/bulk/campaign/'+campaignId+'/failures.xlsx'}><Download size={16}/>Başarısız numaraları Excel indir</a>}</div>
   <details><summary>Her alıcının gönderim durumu</summary><div className="bulk-recipient-list">{(progress.recipients||[]).map((r:Obj)=><div key={r.id}><strong>{r.phone}</strong> · {messageLabels[r.status]||r.status}{r.error?' · '+r.error:''}{r.next_attempt?' · Yeniden deneme zamanı: '+new Date(r.next_attempt).toLocaleString('tr-TR'):''}</div>)}</div><div className="approval-actions"><button disabled={recipientPage<=1} onClick={()=>setRecipientPage(p=>p-1)}>Önceki</button><span>Sayfa {progress.recipient_page||1} / {progress.recipient_pages||1}</span><button disabled={recipientPage>=(progress.recipient_pages||1)} onClick={()=>setRecipientPage(p=>p+1)}>Sonraki</button></div></details>
   {!!progress.failures.length&&<details open><summary>Başarısız numaralar ve hata sebepleri</summary><div className="bulk-recipient-list">{progress.failures.map((r:Obj)=><div key={r.phone}><strong>{r.phone}</strong> · {r.error||r.status}</div>)}</div></details>}
  </section>}
  {review&&<div className="modal-backdrop"><section className="modal bulk-confirm-modal"><h2>Alıcıları ve mesajı onayla</h2><p><strong>{review.count} benzersiz ve izinli numara</strong> · {selected?.name} · {selected?.language}</p><TemplateFields template={selected as any} values={values} onChange={()=>{}} file={mediaFile} disabled/><p>{review.cost_notice}</p><details><summary>Alıcı numaralarını göster</summary><div className="bulk-recipient-list">{review.recipients.map((n:string)=><div key={n}>{n}</div>)}</div><small>İlk 200 alıcı gösterilir.</small></details>
   <details><summary>Önce tek numaraya deneme gönder (isteğe bağlı)</summary><p>Bu işlem canlı modda gerçek mesaj gönderir. Deneme alıcısı toplu gönderimde tekrar hedeflenmez; API kabulü teslimat anlamına gelmez.</p><label className="simple-field">İzinli listedeki deneme numarası<input value={testPhone} onChange={e=>setTestPhone(e.target.value)} inputMode="tel"/></label><button disabled={busy||progress?.test_only||progress?.started} onClick={()=>void begin(true)}>Tek numaraya {review.dry_run?'simülasyon':'gerçek deneme'} gönder</button></details>
   {progress?.test_only&&<p>Deneme: {labels[progress.campaign.status]} · API kabulü {progress.accepted} · teslim {progress.delivered} · okundu {progress.read}. Bu alıcı tekrar gönderilmez.</p>}
   {review.dry_run&&<p>DRY_RUN açık: yalnızca simülasyon yapılır.</p>}
   <div className="modal-actions"><button disabled={busy} onClick={()=>setReview(null)}>Vazgeç</button><button className="button-green" disabled={busy||progress?.test_only&&['running','paused','scheduled'].includes(progress.campaign.status)} onClick={()=>void begin()}><Send size={17}/>{review.dry_run?'Simülasyonu başlat':'Gönder'}</button></div>
  </section></div>}
 </section>;
}
