import WebhookPanel from './WebhookPanel';
import Workspace from './Workspace';
import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,Users,ShieldCheck,Megaphone,BriefcaseBusiness,Store,MessagesSquare,FileText,Inbox,History,ChartNoAxesCombined,Settings,SlidersHorizontal,ArrowUpRight,Plus,Upload,Download,Search,ChevronRight,LogOut,CheckCircle2,AlertCircle,X,Menu,Send,Clock,MessageCircle,RefreshCw} from 'lucide-react';
import './style.css';
import TestMessagePanel from './TestMessagePanel';
type Row=Record<string,any>;
async function api(path:string,method='GET',body?:any){const r=await fetch('/api'+path,{method,headers:{'X-HYS-Request':'1',...(body instanceof FormData?{}:{'Content-Type':'application/json'})},body:body?body instanceof FormData?body:JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:d.detail?.message?(d.detail.message+(d.detail.code!==undefined?' (Meta hata kodu: '+d.detail.code+')':'')):'İşlem tamamlanamadı. Girilen bilgileri kontrol edin.');return d;}
const nav=[['Genel Bakış',LayoutDashboard],['Müşteriler',Users],['Müşteri İzinleri',ShieldCheck],['Müşteri Kampanyaları',Megaphone],['Personeller',BriefcaseBusiness],['Mağazalar',Store],['Personel Duyuruları',MessagesSquare],['Mesaj Şablonları',FileText],['Gelen Mesajlar',Inbox],['Gönderim Geçmişi',History],['Raporlar',ChartNoAxesCombined],['WhatsApp API Ayarları',Settings],['Sistem Ayarları',SlidersHorizontal]] as const;
const labels:Row={draft:'Taslak',scheduled:'Planlandı',running:'Gönderiliyor',paused:'Duraklatıldı',cancelled:'İptal edildi',completed:'Tamamlandı',queued:'Kuyrukta',retry:'Tekrar bekliyor',sending:'İşleniyor',accepted:'API kabul etti',sent:'Gönderildi',delivered:'Teslim edildi',read:'Okundu',failed:'Başarısız',blocked:'Engellendi',uncertain:'Sonuç belirsiz',dry_run:'DRY_RUN',received:'Gelen',unverified:'Doğrulanmadı',verified:'Doğrulandı',revoked:'İzin geri çekildi',review:'İnceleme bekliyor',APPROVED:'Meta onaylı',LOCAL_DRAFT:'Yerel taslak',PENDING:'Meta incelemesinde',REJECTED:'Reddedildi',MARKETING:'Pazarlama',UTILITY:'Utility',AUTHENTICATION:'Kimlik doğrulama'};
function Badge({value}:{value:string}){return <span className={'badge '+(['verified','APPROVED','delivered','read','completed'].includes(value)?'good':['failed','blocked','revoked','uncertain','REJECTED'].includes(value)?'bad':'neutral')}>{labels[value]||value}</span>}
function Empty({title='Henüz kayıt yok',text='İlk kaydınızı ekleyerek başlayabilirsiniz.'}:{title?:string;text?:string}){return <div className="empty"><Inbox size={32}/><h3>{title}</h3><p>{text}</p></div>}
function App(){
 const [setup,setSetup]=useState<Row|null>(null),[user,setUser]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{setSetup(await api('/setup'));try{setUser(await api('/me'));}catch{}}catch(e){setError(String(e));}finally{setLoading(false)}})()},[]);
 if(loading)return <div className="simple-loading">HYS WhatsApp yükleniyor…</div>;
 if(user)return <Workspace user={user} onLogout={async()=>{try{await api('/logout','POST')}finally{setUser(null)}}}/>;
 return <div className="login"><div className="login-brand"><div className="brand-mark">HYS<span>•</span></div><p>KÖROĞLU MAĞAZACILIK</p><h1>WhatsApp.<br/>Tek bir merkezde.</h1><p>Mesajlar, izinli toplu gönderimler ve bağlantı ayarları.</p><div className="login-foot"><ShieldCheck size={18}/> Resmî WhatsApp Cloud API</div></div><div className="login-form"><MessageCircle className="green" size={34}/><h2>{setup?.required?'Yönetim merkezinizi kurun':'Tekrar hoş geldiniz'}</h2><p>{setup?.required?'İlk yönetici hesabınızı oluşturun.':'Devam etmek için hesabınıza giriş yapın.'}</p>{error&&<div className="error" role="alert">{error}</div>}<Form fields={[{key:'username',label:'Kullanıcı adı',required:true},{key:'password',label:'Parola',type:'password',required:true},...(setup?.required&&setup?.bootstrap_required?[{key:'bootstrap_token',label:'Kurulum anahtarı',type:'password',required:true}]:[])]} initial={{}} busy={busy} button={setup?.required?'Yönetici hesabı oluştur':'Giriş yap'} onSubmit={async v=>{setBusy(true);try{if(setup?.required){await api('/setup','POST',v);setSetup({...setup,required:false})}setUser(await api('/login','POST',v));setError('')}catch(e){setError(String(e))}finally{setBusy(false)}}}/><div className="login-note"><ShieldCheck size={16}/> Güvenli iletişim için izin ve gönderim kontrolleri etkindir.</div></div></div>;
}
function Table({rows,columns}:{rows:Row[];columns:Row[]}){return rows.length?<div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c.key}>{c.render?c.render(r):r[c.key]??'—'}</td>)}</tr>)}</tbody></table></div>:<Empty/>;}
function Pagination({total,number,setNumber}:{total:number;number:number;setNumber:(n:number)=>void}){return <div className="pagination"><span>{total} kayıt · Sayfa {number} / {Math.max(1,Math.ceil(total/50))}</span><div><button className="secondary" disabled={number<=1} onClick={()=>setNumber(number-1)}>Önceki</button><button className="secondary" disabled={number*50>=total} onClick={()=>setNumber(number+1)}>Sonraki</button></div></div>}
function Form({fields,initial,busy,onSubmit,button='Kaydet'}:{fields:Row[];initial:Row;busy:boolean;onSubmit:(v:Row)=>void;button?:string}){const [v,setV]=useState(initial);return <form onSubmit={e=>{e.preventDefault();onSubmit(v);}}><div className="form-grid">{fields.map(f=><label className={f.type==='textarea'?'field full':'field'} key={f.key}>{f.type==='checkbox'?<span className="checkbox-label"><input type="checkbox" checked={!!v[f.key]} onChange={e=>setV({...v,[f.key]:e.target.checked})}/>{f.label}</span>:<><span>{f.label}{f.required&&' *'}</span>{f.options?<select aria-label={f.label+(f.required?' *':'')} required={f.required} value={v[f.key]??''} onChange={e=>setV({...v,[f.key]:e.target.value})}><option value="">Seçiniz</option>{f.options.map(([id,label]:any)=><option key={id} value={id}>{label}</option>)}</select>:f.type==='textarea'?<textarea required={f.required} value={v[f.key]??''} placeholder={f.placeholder} onChange={e=>setV({...v,[f.key]:e.target.value})}/>:<input required={f.required} type={f.type||'text'} value={v[f.key]??''} min={f.type==='number'?1:undefined} placeholder={f.placeholder} minLength={f.type==='password'?3:undefined} onChange={e=>setV({...v,[f.key]:e.target.value})}/>}</>}</label>)}</div><button className="primary form-submit" disabled={busy}>{busy?'İşleniyor…':button}<ChevronRight size={16}/></button></form>}
createRoot(document.getElementById('root')!).render(<App/>);
